### ISSUE TITLE
creating service with ServiceGraphName annotation 

### ISSUE THREAD

**Issue by z2mi** [noironetworks/aci-containers#1474]
Hi, 

I want to create kube service with this manifest :
```
apiVersion: v1
kind: Service
metadata:
  name: blue-service
  namespace: kuard
  annotations:
    opflex.cisco.com/lb-ipam-ips:  x.x.x.x
    opflex.cisco.com/ext_service_contract_scope: global
    opflex.cisco.com/service-graph-name: "present"
spec:
  selector:
    app: kuard-blue
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
```
and I am getting following error in controller pod :
`Could not update dn uni/tn-<tenant>/brc-<tenant>_svc_kuard_blue-service" code=0 mod=APICAPI status=400 text="unknown attribute 'customSG' in element 'vzRsSubjGraphAtt'
`
and this error apparently caused by this [method](https://github.com/noironetworks/aci-containers/blob/fa900dc2c35ee7cd9aa35d4e0c86df965c701e48/pkg/apicapi/apic_types.go#L990)

I checked with APIC Object Store and there is no 'customSG' attribute in 'vzRsSubjGraphAtt' instances

before applying service manifest, I created Service Graph Template with node "loadbalancer" ( Device `<tenant>_svc_global` ) and also created contract `<tenant>_svc_kuard-blue-service` with "loadbalancedservice" as Subject and set mentioned Service Graph in it.

APIC firemware version : 6.1(1f)
Controller pod Image :  quay.io/noiro/aci-containers-controller:6.1.1.1.81c2369
