### ISSUE TITLE
Supported docker-versions

### ISSUE THREAD

**Issue by headconnect** [noironetworks/aci-containers#223]
Hi,

We encountered a strange issue in that kubernetes pods provided through DaemonSets would not have visible IPs in APIC, and wouldn't be reachable in the cluster (either externally or by pinging/telnet/curl otherwise from another pod).  The exact same pods provided through a Deployment (even at scale 2x number of nodes) would all work perfectly fine.

Additionally, LoadBalancer IPs would be delegated to services, but those ips would not be reachable either (clusterIP would work, as well as the NodePort created by the LoadBalancer - just that the ACI provided IP would not work). 

This is with acc-provision 1.9.9 (also tested 1.9.7) against apic 4.0(2c). 

This issue seems to occur with kubernetes 1.12 which now supports newer versions of docker (i.e. 18.06 for instance, rather than the 17.03 which has been the max until then). 

The question is then - have you tested this setup with daemon sets, and have you tested it with kubernetes 1.12 with newer versions of docker? Are there any limitations that we should be aware of?

**Comment by headconnect** [comment]
Slight update, doesn't seem to be working on 12.4 and docker 17.3 either.

Noticed that the controller logs (acc.log from acikubectl debug output) says (for the daemonset created pods):

 "Failed to update pod: (podname) is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations).

aci-containers-host.log gives a normal message with "successfully configured contiainer interface" and "adding endpoint" for the pods

aci-containers-openvswitch.log has nothing relevant that I can see.

opflex-agent.log gives a normal message with "Updated endpoint Endpoint[....."

As for node commands - they don't seem to indicate anything out of the ordinary to my untrained eyes.. 

In any event - that "failed to update pod" part does seem interesting.

**Comment by jojimt** [comment]
https://github.com/noironetworks/aci-containers/pull/195 will address this. Can you share the daemonset spec in question?

**Comment by headconnect** [comment]
Think you're right, and it will likely resolve the permission aspect from the logs.  However, I don't quite see how it will address the LoadBalancer issue, but we'll keep working on identifying that until we can find a trace.

DS as follows:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    component: nginx
  name: nginx
  namespace: verify
spec:
  selector:
    matchLabels:
      component: nginx
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
      - image: nginx:1.15
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 28Mi
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
```
(this has been entered by hand, and should be textually correct, though there may be some yaml syntax issues in this version - the source is entirely valid and correct, and is exactly the DS I've used for verification)
